name: p2p_call_sample
description: P2P Calls Sample

version: 1.5.3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectycube_sdk: ^2.5.0
#  connectycube_sdk:
#    path: ../../flutter-sdk
  shared_preferences: ^2.0.15
  connectycube_flutter_call_kit: ^2.2.4
#  connectycube_flutter_call_kit:
#    path: ../../connectycube-flutter-call-kit/connectycube_flutter_call_kit
  flutter_background: ^1.2.0
  permission_handler: ^10.0.1
  device_info_plus: ^8.2.2
  package_info_plus: ^4.0.2
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^15.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true